### PR TITLE
fix(ns5-android): make lib calling callbacks

### LINKED ISSUE #3495: NC native android - fix callback calls

### PR DESCRIPTION
**Pull request by doums**
# Description

Closes: #3495

### CODE REVIEW

File: sdk/lib/socks5-listener/src/android.rs [hunk 1]
```diff
@@ -47,53 +42,50 @@ pub unsafe extern "C" fn Java_net_nymtech_nyms5_NymProxy_run(
 
     log::debug!("using sp {}", sp_input);
 
-    // TODO pass this callback to blocking_run_client
-    env.call_method(cb_object, "onStart", "()V", &[])
-        .expect("failed to call Java callbacks");
-
     let service_provider = char_p::new(sp_input.as_str());
+
+    let arced = Arc::new(Mutex::new(env));
```
Comment (jstuczyn) [inline sdk/lib/socks5-listener/src/android.rs:47]: You'd probably want to use tokio's async aware mutexes because the std ones could theoretically block the runtime

File: sdk/lib/socks5-listener/src/lib.rs [hunk 2]
```diff
@@ -107,13 +103,15 @@ pub fn get_client_state() -> ClientState {
...
     storage_directory: Option<char_p::Ref<'_>>,
     service_provider: Option<char_p::Ref<'_>>,
-    on_start_callback: StartupCallback<'static>,
-    on_shutdown_callback: ShutdownCallback<'static>,
-) {
+    on_start_callback: F,
+    on_shutdown_callback: S,
+) where
+    F: FnMut(String) + Send + 'static,
+    S: FnMut() + Send + 'static,
```
Comment (jstuczyn) [inline sdk/lib/socks5-listener/src/lib.rs:113]: nitpicky: does it have to be an `FnMut` or could we get away with a normal `Fn` ( or maybe even something like we had initially, i.e. `extern "C" fn`)?

Comment (doums) [reply sdk/lib/socks5-listener/src/lib.rs:113]: `FnMut` is needed as for android we are using JNI to call java methods and the signature takes a `&mut self`
https://docs.rs/jni/0.21.1/jni/struct.JNIEnv.html#method.call_method

> or maybe even something like we had initially, i.e. extern "C" fn

Im not sure, can you share a snippet using `extern "C" fn` please?

File: sdk/lib/socks5-listener/src/android.rs (hunk 1 above)
Comment (doums) [reply sdk/lib/socks5-listener/src/android.rs:47]: Im not so sure, reading the ref https://docs.rs/tokio/latest/tokio/sync/struct.Mutex.html#which-kind-of-mutex-should-you-use I think using async mutex here does not worth it?
what do you think?

File: sdk/lib/socks5-listener/src/lib.rs (hunk 2 above)
Comment (jstuczyn) [reply sdk/lib/socks5-listener/src/lib.rs:113]: Ah, if we need it for android, then the other way will definitely not work
