### PR TITLE
fix(wallet-delegation): add error feedback on wrong address

### LINKED ISSUE #1509: Wallet - Delegation on wrong mixnode address cause a silent error
When trying to delegate on a wrong node address (for example a node address that does not exist in the given network), no error feedback is shown to the user.

but an error is printed in the console:
```
[Error] Abci query failed with code 18 - failed to execute message; message index: 0: MIXNET (21): Mixnode (xxxx) does not exist: execute wasm contract failed: invalid request
```

### PR DESCRIPTION
**Pull request by doums**
# Description

Add an error description using a dialog.

Closes: #1509 

image

### CODE REVIEW

File: nym-wallet/src/components/Delegation/DelegationModal.tsx [hunk 1]
```diff
@@ -48,20 +48,9 @@ export const DelegationModal: React.FC<
...
-          </Typography>
-          {children}
-          <Button variant="contained" onClick={onClose}>
-            Close
-          </Button>
-        </Box>
-      </Modal>
+      <ErrorModal message="Oh no! Something went wrong..." error={message} sx={sx} open={open} onClose={onClose}>
+        {children}
+      </ErrorModal>
```
Comment (fmtabbara) [inline nym-wallet/src/components/Delegation/DelegationModal.tsx]: :sunglasses:

**Review by fmtabbara — APPROVED** [review]
