### PR TITLE
Bug fix: wallet delegations list is empty when RPC node doesn't hold block

### LINKED ISSUE #4540: [Issue] Delegation not displayed in wallet, contrary to explorer's display.
**Describe the issue**
When users accessed their Nym Wallet to check their delegations, there wasn't any information about them. Nothing was shown.

**Expected behaviour**

The expected behavior entailed the clear presentation of delegations within the interface, accompanied by comprehensive information including claimable rewards, current epoch status, and the availability of an unstake option.

**Steps to Reproduce**

Open the wallet application on your device.
Enter your mnemonic phrase or password to authenticate your account.
Navigate to the delegation section within the application interface.

**Screenshots**
A screenshot isn't necessary because the delegation page doesn't display the wallet address, making it impossible to compare with the explorer. Personally, I (Merve) cross-referenced the user's wallet address in the explorer and their wallet screenshot. While the explorer showed the delegation, the wallet did not.

**Which area of Nym were you using?**
Windows 10. 
Nym wallet 1.2.12

### PR DESCRIPTION
**Pull request by mmsinclair**
# Description

Adds better error handling and display when queries for delegations fail.

The root cause of #4540 is because the RPC node that is queried to find the block time of the delegation has pruned old blocks, and returns an error that the block doesn't exist. This breaks the loop that processes delegations and none are displayed.

This has been fixed by providing null values when queries fail for each delegation, with a tooltip that shows details of the errors encountered.

Closes: #4540

### CODE REVIEW

File: nym-wallet/src/components/Delegation/DelegationList.tsx [hunk 1]
```diff
@@ -105,6 +108,12 @@ export const DelegationList: FCWithChildren<{
   return (
     <TableContainer>
       {isLoading && <LoadingModal text="Please wait. Refreshing..." />}
+      <ErrorModal
+        open={Boolean(delegationItemErrors)}
+        title={`Delegation errors for Node ID ${delegationItemErrors?.nodeId || 'unknown'}`}
+        message={delegationItemErrors?.errors || 'opps'}
```
Comment (mmsinclair) [inline nym-wallet/src/components/Delegation/DelegationList.tsx]:
```suggestion
        message={delegationItemErrors?.errors || 'oops'}
```

Fix typo

**Comment by tommyv1987** [comment]
**Testing Completion Date:** 07,05,2024

**Testing Steps Performed:**
1. Run the wallet build in dev mode.
2. Proceed to an account with lots of delegations.
3. Monitor the output log for the amended code. Ensure it does not prevent the wallet from displaying necessary information when navigating to and from the delegation page.

**Validation:**
- [x] Test Passed
- [ ] Issues Found (Please specify below)

**Notes (if any):**
This is looking good to me. I've tested this on Windows and on Mac, I'm not experiencing the issues that were present. This is looking good to be shipped.

**Attachments (if applicable):**
[Attach any relevant screenshots, logs, or documents.]

**Review by tommyv1987 — APPROVED** [review]
