### PR TITLE
Fix uptime integer division, change lambda and sigma from ticked to regular

### LINKED ISSUE #1286: Fix integer division problem for performance and operator cost parts of the rewards calculation

### PR DESCRIPTION
**Pull request by durch**
# Description

Fixes: [1286](https://github.com/nymtech/nym/issues/1286)

+ Adds `estimated_node_profit` and `estimated_operator_cost` to `reward-estimate` response.
+ Fixes` estimated_delegator_reward` to be calculated from `node_profit`
+ Switch to `lambda` and `sigma` for operator and delegator reward calculation, instead of `lambda'` and `sigma'`

# Checklist:

- [x] added a changelog entry to `CHANGELOG.md`

### CODE REVIEW

File: common/cosmwasm-smart-contracts/mixnet-contract/src/mixnode.rs [hunk 1]
```diff
@@ -427,20 +427,31 @@ impl MixNodeBond {
     pub fn estimate_reward(
         &self,
         params: &RewardParams,
-    ) -> Result<(u64, u64, u64), MixnetContractError> {
+    ) -> Result<(u64, u64, u64, u64, u64), MixnetContractError> {
```
Comment (jstuczyn) [inline common/cosmwasm-smart-contracts/mixnet-contract/src/mixnode.rs]: I think we reached a point where those should probably get extracted to some separate struct, returning a tuple with 5 values seem to be rather confusing : )
