### PR TITLE
Wallet: Fix delegation sorting for Cost Params

### LINKED ISSUE #3981: Wallet - ordering the delegations by Cost does not seem to work correctly

### PR DESCRIPTION
**Pull request by fmtabbara**
# Description

Fix sorting delegations by `operator cost`.

Closes: #3981 

# Checklist:

- [ ] added a changelog entry to `CHANGELOG.md`

### CODE REVIEW

File: nym-wallet/src/hooks/useSortDelegations.tsx [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+
+export const useSortDelegations = (delegationItems: TDelegations, order: Order, orderBy: SortingKeys) => {
+  const unbondedDelegations = delegationItems.filter((delegation) => !delegation.node_identity);
+  const delegations = delegationItems.filter((delegation) => delegation.node_identity);
+
+  const mapOrderBy = (key: SortingKeys) => {
+    if (key === 'amount') return 'delegationValue';
+    if (key === 'unclaimed_rewards') return 'operatorReward';
+    if (key === 'profit_margin_percent') return 'profitMarginValue';
+    if (key === 'operating_cost') return 'operatorCostValue';
```
Comment (doums) [inline nym-wallet/src/hooks/useSortDelegations.tsx]: Suggestion: use a switch case, or even a simple object to handle the mapping:

```
const keyMap = {
  amount: 'delegationValue',
  ...
}
return keyMap[key] || key;
```

**Review by doums — APPROVED** [review]

**Review by doums — APPROVED** [review]

**Review by tommyv1987 — APPROVED** [review]
